---
fixtures:
  symlinks:
    role: "#{source_dir}/dist/role"
    profile: "#{source_dir}/dist/profile"
  repositories:
    accounts:
      repo: https://github.com/puppetlabs/puppetlabs-accounts
      ref: 1.1.0
    apt:
      repo: https://github.com/puppetlabs/puppetlabs-apt
      ref: 2.3.0
    concat:
      repo: https://github.com/puppetlabs/puppetlabs-concat
      ref: 2.2.0
    git:
      repo: https://github.com/puppetlabs/puppetlabs-git
      ref: 0.5.0
    inifile:
      repo: https://github.com/puppetlabs/puppetlabs-inifile
      ref: 1.6.0
    mysql:
      repo: https://github.com/puppetlabs/puppetlabs-mysql
      ref: 3.10.0
    ntp:
      repo: https://github.com/puppetlabs/puppetlabs-ntp
      ref: 6.0.0
    ruby:
      repo: https://github.com/puppetlabs/puppetlabs-ruby
      ref: 0.6.0
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib
      ref: 4.15.0
    vcsrepo:
      repo: https://github.com/puppetlabs/puppetlabs-vcsrepo
      ref: 1.5.0
    nfs:
      repo: https://github.com/derdanne/puppet-nfs
      ref: 1.0.2
    docker:
      repo: https://github.com/vladgh/garethr-docker
      ref: master
    hiera:
      repo: https://github.com/voxpupuli/puppet-hiera
      ref: v2.4.0
    wget:
      repo: https://github.com/maestrodev/puppet-wget
      ref: v1.7.3
    archive:
      repo: https://github.com/voxpupuli/puppet-archive
      ref: v1.3.0
    swap_file:
      repo: https://github.com/petems/petems-swap_file
      ref: v3.0.2
    rsyslog:
      repo: https://github.com/saz/puppet-rsyslog
      ref: v5.0.0
    python:
      repo: https://github.com/stankevich/puppet-python
      ref: 1.18.2
    r10k:
      repo: https://github.com/voxpupuli/puppet-r10k
      ref: v4.1.0
    fail2ban:
      repo: https://github.com/dhoppe/puppet-fail2ban
      ref: 1.3.4
    gnupg:
      repo: https://github.com/n1tr0g/golja-gnupg
      ref: 1.2.3
    cloudwatchlogs:
      repo: https://github.com/kemra102/puppet-cloudwatchlogs
      ref: v2.3.1
    rvm:
      repo: https://github.com/maestrodev/puppet-rvm
      ref: v1.13.1
    ssh:
      repo: https://github.com/saz/puppet-ssh
      ref: v3.0.1
    sudo:
      repo: https://github.com/saz/puppet-sudo
      ref: v4.1.0
    samba:
      repo: https://github.com/thias/puppet-samba
      ref: 1.0.0
    unattended_upgrades:
      repo: https://github.com/voxpupuli/puppet-unattended_upgrades
      ref: v2.2.0
    extlib:
      repo: https://github.com/voxpupuli/puppet-extlib
      ref: v1.1.0
    make:
      repo: https://github.com/voxpupuli/puppet-make
      ref: v1.1.0
    sysctl:
      repo: https://github.com/fiddyspence/puppet-sysctl
      ref: 1.1.0
    portage:
      repo: https://github.com/gentoo/puppet-portage
      ref: 2.4.0
    staging:
      repo: https://github.com/voxpupuli/puppet-staging
      ref: v2.2.0
    firewall:
      repo: https://github.com/puppetlabs/puppetlabs-firewall
      ref: 1.8.2
    gcc:
      repo: https://github.com/puppetlabs/puppetlabs-gcc
      ref: 0.3.0
    pe_gem:
      repo: https://github.com/puppetlabs/puppetlabs-pe_gem
      ref: 0.1.2
    epel:
      repo: https://github.com/stahnma/puppet-module-epel
      ref: 1.2.2
