language: ruby
bundler_args: --without development system_tests

rvm:
  - 1.9.3
  - 2.1.6

env:
  matrix:
    - PUPPET_GEM_VERSION="~> 3.0"
    - PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES=yes

matrix:
  fast_finish: true

script: 'cd dist/profile && bundle exec rake test'
