sudo: false

language: ruby

rvm:
  - 2.1.7

env:
  - PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES=yes

install: 'cd dist/profile && bundle install --without development system_tests'

script: 'cd dist/profile && bundle exec rake test'
