sudo: required
dist: trusty

language: ruby

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.4.2

install:
  - sudo add-apt-repository -y ppa:git-core/ppa # Add repo but let docker update
  - wget -qO- https://get.docker.com/ | sh
  - sudo wget -qO /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m`
  - sudo chmod +x /usr/local/bin/docker-compose
  - sudo apt-get install git # now that docker updated apt we can install git

script:
  - sudo docker version
  - sudo docker-compose version
  - sudo git version
