sudo: false

language: ruby

install: 'cd dist/profile && bundle install --without development'

matrix:
  fast_finish: true
  include:
  - rvm: 2.1.7
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES=yes
    script: 'ls -lah && cd dist/profile && bundle exec rake test'
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-14-04-x64"
    script: 'ls -lah && cd dist/profile && bundle exec rake acceptance'
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set="debian-8-2-x64"
    script: 'cd dist/profile && bundle exec rake acceptance'
