language: ruby
bundler_args: --without development system_tests

rvm:
  - 2.1.6

env:
  - PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES=yes

matrix:
  fast_finish: true

script: 'cd dist/profile && bundle exec rake test'
