sudo: required

services:
  - docker

before_install:
  - cat /etc/apt/sources.list.d/docker-source.list
  - cat /etc/apt/sources.list.d/git-ppa-source.list
  - sudo apt-get update && sudo apt-get upgrade
