sudo: false
language: ruby
install:
  - cd dist/profile && bundle install --without development system_tests --path vendor
  - pip install awscli
env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES=yes
script: bundle exec rake test
cache:
  directories:
  - dist/profile/vendor
  - dist/profile/spec/fixtures/modules
deploy:
  provider: s3
  access_key_id: AKIAIGIJGXNDAACN2YNQ
  secret_access_key:
    secure: Vn+E0F4gKcwP26xzjK2wV5Y/1cea0tgP66UerxG7nwFvzvcv6/IgXmW9jDFTYnQ0g+pJuu4YhvfH8Qi59upbVjDnLsvgi4qbSsBnrRSzfsyPTTF3E6sABND/PC0ZO1DroRKQgSJ9Fq6Yd6AZRDZnwEKMq2zdb7lALJjJGb5h66EsioIoUoz2J/oct8G1tKMb2ZRS2EN4djFgVOKkt6PTH+wBm5dMCQ3msUBUAYNc4lL9VXD5Q3W04rFtWFuGmd1upk+xr1uBwbB42ytJITjZgsYi+zxpm8RYhBnx7xj/oldjmeCfR5v0O2mSRHJLBi/mZmAY5Lnycdo/8LgNsbBn1ylpuDD9aU3b96eLV29AGNOjSIkbVkasH0105UowEnJ3Q4EQ87ys5PxGH9Eat1i4DVTprLPW1G0FhiDfSwDRUJt+Q5GFdYnBOjrnuQsfPsdp782Uh7Ggv3llH+uCkLjTrQuHjtQos0xkeM8pXan3BrfB/fzQ3eMb9NnBr8xuBljlkRk5Potr/DEFZBpr552Y5A9yf/RTZF/9ZVOa/O2437GsYVB3TJN2mssxrYp488dDkLxyvSaXj3Ves9vnHO5oWqTRinhI9gz3VkUT6sFv7rD3JzogwIqfwFq2Z+a5D3WPcygYMue65pxB18WOq3OeJUyBQ8yx2VqQZQboAR7hjxE=
  bucket: vladgh
  acl: private
  local_dir: cfn
  upload-dir: cloudformation
notifications:
  slack:
    secure: PO+9V7wfK1zJZTO3RgewarOo2Uk6bhPXTAUFwDhwEoBnbhOEIq1ItLkOZfXW4LgQ9WpK03x1y9LNA4xHK89Z3yxO/s+/Csf5YOcv9+CUuwQR4vjfiFmedB8DCObGKc5HdsuohJx6G/YyLag8gFTJMGIDyQRN4uodXjrK2NGuMG8QRYhq4qwYtmnw3Q4q3o9Nsso1486qTnbWuRtF78ofgVnBurNYefbOiycGRvX4on2WI8syGcBVLQWIO/9Lc3Nye3arKdvtrVKI15/QM5DpgyPCmSTeqeu122XgVP/vPqYtmBXttU3lTladAq3S5VpMo9DQlltgTLvAl4a8ma+mzqtux1K628tMsAcNLUpcsXYbbUTRQILCmIQlDomC8oQOtSWnYPCtMpTr/5pGElVlNoWUSahlZS/VV9m/1Om64lgFdxY+MI9sI8UlXi6Ny47JfpHp7xQJPe80sFVLtwtrs9ievcEyw1R+9rSL1ASs3JIevKu5q9wTFL8Dy8lzWHlwyth8kkSruzUc7b5wsLpOPhJoKXuEJjY1ac3abgBjuX06Vk0y0y/dJdPDKy3Uo+ajY4IdjoppuJPRklXv77/hU04W8XTlD5eBR+M4tWAsUZgU1GkgtoUV05GSfNwhRfpeqzqqqzVjeUDUmXvhUG1YmkNd3wdRaW6t57iCi7P6ikI=
