sudo: false

language: ruby

rvm:
  - 2.1.7

env:
  - PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES=yes

bundler_args: --gemfile dist/profile/Gemfile --without development system_tests

cache: bundler

script: 'cd dist/profile && bundle exec rake test'
