sudo: required

language: ruby

services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.4.0

install:
  - sudo add-apt-repository -y ppa:git-core/ppa
  - sudo apt-get update
  - sudo apt-get install git
  - wget -qO- https://get.docker.com/ | sh
  - sudo wget -qO /usr/local/bin/docker-compose https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m`
  - sudo chmod +x /usr/local/bin/docker-compose

script:
  - git version
  - docker version
  - docker-compose version
