language: ruby
rvm: 2.2
sudo: false
branches:
  except:
    - /^v\d/
before_install: gem update bundler
cache:
  directories:
    - dist/profile/vendor/bundle
    - dist/profile/spec/fixtures/modules
matrix:
  fast_finish: true
  include:
  - env: PUPPET_GEM_VERSION="~> 4.0" CI_NODE_TOTAL=2 CI_NODE_INDEX=1
    install: bundle install --without development system_tests --path vendor/bundle
    script: bundle exec rake test
  - env: PUPPET_GEM_VERSION="~> 4.0" CI_NODE_TOTAL=2 CI_NODE_INDEX=2
    install: bundle install --without development system_tests --path vendor/bundle
    script: bundle exec rake test
  - env: PUPPET_INSTALL_TYPE=agent ORDERING=manifest BEAKER_debug=yes BEAKER_set=docker/mini
    install: bundle install --without development --path vendor/bundle
    script: bundle exec rake integration
  - env: PUPPET_INSTALL_TYPE=agent ORDERING=manifest BEAKER_debug=yes BEAKER_set=docker/ogstor
    install: bundle install --without development --path vendor/bundle
    script: bundle exec rake integration
  - env: PUPPET_INSTALL_TYPE=agent ORDERING=manifest BEAKER_debug=yes BEAKER_set=docker/rhea
    install: bundle install --without development --path vendor/bundle
    script: bundle exec rake integration
notifications:
  webhooks:
    urls: https://puppet.ghn.me/travis
  slack:
    secure: PO+9V7wfK1zJZTO3RgewarOo2Uk6bhPXTAUFwDhwEoBnbhOEIq1ItLkOZfXW4LgQ9WpK03x1y9LNA4xHK89Z3yxO/s+/Csf5YOcv9+CUuwQR4vjfiFmedB8DCObGKc5HdsuohJx6G/YyLag8gFTJMGIDyQRN4uodXjrK2NGuMG8QRYhq4qwYtmnw3Q4q3o9Nsso1486qTnbWuRtF78ofgVnBurNYefbOiycGRvX4on2WI8syGcBVLQWIO/9Lc3Nye3arKdvtrVKI15/QM5DpgyPCmSTeqeu122XgVP/vPqYtmBXttU3lTladAq3S5VpMo9DQlltgTLvAl4a8ma+mzqtux1K628tMsAcNLUpcsXYbbUTRQILCmIQlDomC8oQOtSWnYPCtMpTr/5pGElVlNoWUSahlZS/VV9m/1Om64lgFdxY+MI9sI8UlXi6Ny47JfpHp7xQJPe80sFVLtwtrs9ievcEyw1R+9rSL1ASs3JIevKu5q9wTFL8Dy8lzWHlwyth8kkSruzUc7b5wsLpOPhJoKXuEJjY1ac3abgBjuX06Vk0y0y/dJdPDKy3Uo+ajY4IdjoppuJPRklXv77/hU04W8XTlD5eBR+M4tWAsUZgU1GkgtoUV05GSfNwhRfpeqzqqqzVjeUDUmXvhUG1YmkNd3wdRaW6t57iCi7P6ikI=
