language: ruby

install: 'cd dist/profile && bundle install --without development --path vendor/bundle'

cache:
  directories:
    - dist/profile/vendor/bundle
    - dist/profile/spec/fixtures/modules

matrix:
  fast_finish: true
  include:
  - rvm: 2.1.7
    sudo: false
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES=yes
    script: 'bundle exec rake test'
  - rvm: default
    sudo: required
    services: docker
    env: BEAKER_set="ubuntu-trusty-x64"
    script: 'bundle exec rake acceptance'
