version: '2'

services:
  r10k:
    image: vladgh/r10k:latest
    hostname: r10k-agent
    volumes_from:
      - data
    environment:
      ENVTYPE: "$ENVTYPE"
    working_dir: /vpm
    entrypoint: /vpm/bin/run-r10k-agent
    restart: 'no'
  server:
    image: vladgh/puppetserver:aws
    hostname: puppet.ghn.me
    ports:
      - '8140:8140'
    volumes_from:
      - data
    environment:
      ENVTYPE: "$ENVTYPE"
      AUTOSIGN: '/vpm/bin/csr-sign'
      AUTOSIGN_CFG: "/etc/puppetlabs/private/${ENVTYPE}/csr_cfg.yaml"
      DNS_ALT_NAMES: 'puppet,puppet.ghn.me,puppetca,puppetca.ghn.me'
      JAVA_ARGS: '-Xms768m -Xmx768m'
    entrypoint: /vpm/bin/run-puppetserver
    restart: 'on-failure:5'
  logs:
    hostname: log-agent
    image: gliderlabs/logspout:latest
    volumes_from:
      - data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      ENVTYPE: "$ENVTYPE"
    entrypoint: /vpm/bin/run-log-agent
    restart: 'on-failure:5'
  data:
    image: vladgh/awscli:latest
    hostname: data-agent
    volumes:
      - ~/.aws:/root/.aws
      - .:/vpm
      - ./hiera.yaml:/etc/puppetlabs/puppet/hiera.yaml
      - ./r10k.yaml:/etc/puppetlabs/r10k/r10k.yaml
      - code:/etc/puppetlabs/code
      - ssl:/etc/puppetlabs/puppet/ssl
      - private:/etc/puppetlabs/private
      - hieradata:/etc/puppetlabs/hieradata
      - /var/local
      - /opt/vgs
    environment:
      ENVTYPE: "$ENVTYPE"
    working_dir: /vpm
    entrypoint: /vpm/bin/run-data-agent
    restart: 'no'

volumes:
  code:
  ssl:
  private:
  hieradata:
