version: '2'

services:
  agent:
    image: vladgh/puppet:latest
    volumes:
      - ./bin:/scripts
    environment:
      ROLE: 'none'
    links:
      - server:puppet
    entrypoint: bash -c '/scripts/wait-for-puppetserver puppet puppet agent --test'
  server:
    image: vladgh/puppetserver:aws
    ports:
      - '8140:8140'
    volumes_from:
      - r10k
    volumes:
      - ./hiera.yaml:/etc/puppetlabs/puppet/hiera.yaml
    environment:
      AUTOSIGN: 'true'
      JAVA_ARGS: '-Xms512m -Xmx512m'
  r10k:
    image: vladgh/r10k:latest
    volumes:
      - .:/etc/puppetlabs/code/environments/production
    working_dir: /etc/puppetlabs/code/environments/production
    command: puppetfile install --verbose
