version: '2'

services:
  r10k:
    image: vladgh/r10k:latest
    hostname: r10k-agent
    volumes:
      - ~/.aws:/root/.aws
      - .:/vpm
      - ssl:/etc/puppetlabs/puppet/ssl
      - code:/etc/puppetlabs/code
      - hieradata:/etc/puppetlabs/hieradata
      - /var/local
      - /opt/vgs
    working_dir: /vpm
    entrypoint: /vpm/bin/run-r10k-agent
    restart: 'no'
  server:
    image: vladgh/puppetserver:aws
    hostname: puppet.ghn.me
    ports:
      - '8140:8140'
    volumes_from:
      - r10k
    environment:
      AUTOSIGN: '/vpm/bin/csr-sign'
      AUTOSIGN_CFG: '/vpm/.private/csr_cfg.yaml'
      JAVA_ARGS: '-Xms768m -Xmx768m'
    entrypoint: /vpm/bin/run-puppetserver
    restart: 'on-failure:5'
  logs:
    hostname: log-agent
    image: gliderlabs/logspout:latest
    volumes_from:
      - r10k
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /vpm/bin/run-log-agent
    restart: 'on-failure:5'

volumes:
  ssl:
  code:
  hieradata:
