version: '2'

services:
  server:
    image: vladgh/puppetserver:aws
    hostname: puppet.ghn.me
    ports:
      - '8140:8140'
    volumes_from:
      - data
    environment:
      AUTOSIGN: '/vpm/bin/csr-sign'
      AUTOSIGN_CFG: '/etc/puppetlabs/private/csr_cfg.yaml'
      DNS_ALT_NAMES: 'puppet,puppet.ghn.me,puppetca,puppetca.ghn.me'
      JAVA_ARGS: '-Xms768m -Xmx768m'
    entrypoint: /vpm/bin/run-puppetserver
  logs:
    hostname: log-agent
    image: gliderlabs/logspout:latest
    volumes_from:
      - data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: .private/logging.env
    entrypoint: /vpm/bin/run-log-agent
  sslsync:
    image: vladgh/s3sync:latest
    hostname: ssl-sync-agent
    volumes_from:
      - data
    environment:
      S3PATH: "$S3_SSL"
      WATCHDIR: /etc/puppetlabs/puppet/ssl
  r10k:
    image: vladgh/r10k:latest
    hostname: r10k-agent
    volumes_from:
      - data
    entrypoint: /vpm/bin/run-r10k-agent
  data:
    image: vladgh/awscli:latest
    hostname: data-agent
    volumes:
      - ~/.aws:/root/.aws
      - /etc/localtime:/etc/localtime:ro
      - /opt/vgs:/opt/vgs
      - .:/vpm
      - ./.private:/etc/puppetlabs/private
      - ./hieradata:/etc/puppetlabs/hieradata
      - ./hiera.yaml:/etc/puppetlabs/puppet/hiera.yaml
      - ./r10k.yaml:/etc/puppetlabs/r10k/r10k.yaml
      - ssl:/etc/puppetlabs/puppet/ssl
      - code:/etc/puppetlabs/code
      - /var/local

volumes:
  ssl:
  code:
