version: '2'

services:
  puppetserver:
    image: vladgh/puppetserver:latest
    volumes:
      - code:/etc/puppetlabs/code/environments/production
      - hieradata:/etc/puppetlabs/hieradata/environments/production
      - ssl:/etc/puppetlabs/puppet/ssl
      - ./hiera.yaml:/etc/puppetlabs/puppet/hiera.yaml
      - ./r10k.yaml:/etc/puppetlabs/r10k/r10k.yaml
      - ./bin/sign:/etc/puppetlabs/csr/sign
    ports:
      - '8140:8140'
    networks:
      - main

networks:
  main:

volumes:
  code:
  hieradata:
  ssl:
