version: '2'

services:
  server:
    image: vladgh/puppetserver:aws
    hostname: puppet.ghn.me
    ports:
      - '8140:8140'
    volumes_from:
      - r10k
    environment:
      AUTOSIGN: 'true'
      JAVA_ARGS: '-Xms256m -Xmx256m'
  r10k:
    image: vladgh/r10k:latest
    hostname: r10k-agent
    volumes:
      - .:/etc/puppetlabs/code/environments/production
      - ./hiera.yaml:/etc/puppetlabs/puppet/hiera.yaml
      - ./hieradata:/etc/puppetlabs/hieradata/production
    command: puppetfile install
    working_dir: /etc/puppetlabs/code/environments/production
