version: '2'

services:
  server:
    image: vladgh/vpm-server:latest
    hostname: puppet.ghn.me
    ports:
      - '8140:8140'
    volumes_from:
      - data
    environment:
      AUTOSIGN: '/usr/local/bin/csr-sign'
      AUTOSIGN_CFG: '/etc/puppetlabs/vault/production/csr_cfg.yaml'
      DNS_ALT_NAMES: 'puppet,puppet.ghn.me,puppetca,puppetca.ghn.me'
      JAVA_ARGS: '-Xms1G -Xmx1G'
    entrypoint: sh -c "until [ -s /var/local/deployed_r10k ]; do echo 'Waiting for R10K'; sleep 5; done; /entrypoint.sh puppetserver foreground"
  logs:
    hostname: log-agent
    image: gliderlabs/logspout:latest
    volumes_from:
      - data
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: sh -c "until [ -s /etc/puppetlabs/vault/logging.env ]; do echo 'Waiting for data'; sleep 5; done && set -a && . /etc/puppetlabs/vault/logging.env && /bin/logspout syslog://$${LOG_SERVER_ADDRESS}:$${LOG_SERVER_PORT}"
  ssl:
    image: vladgh/s3sync:latest
    hostname: ssl-sync-agent
    volumes_from:
      - data
    entrypoint: sh -c "until [ -s /etc/puppetlabs/vault/ssl.env ]; do echo 'Waiting for data'; sleep 5; done && set -a && . /etc/puppetlabs/vault/ssl.env && /entrypoint.sh"
  data:
    image: vladgh/vpm-data:latest
    hostname: data-agent
    environment:
      AWS_ASSETS_BUCKET: vladgh
    working_dir: /opt/vpm
    volumes:
      - .:/opt/vpm
      - ssl:/etc/puppetlabs/puppet/ssl
      - code:/etc/puppetlabs/code
      - vault:/etc/puppetlabs/vault
      - hieradata:/etc/puppetlabs/hieradata
      - ../vgs:/opt/vgs:ro
      - ~/.aws:/root/.aws:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/local

volumes:
  ssl:
  code:
  vault:
  hieradata:
