version: '2'

services:
  server:
    image: vladgh/vpm-server:latest
    hostname: puppet.ghn.me
    ports:
      - '8140:8140'
    volumes_from:
      - data
    environment:
      AUTOSIGN: '/usr/local/bin/csr-sign'
      AUTOSIGN_CFG: '/etc/puppetlabs/vault/csr_cfg.yaml'
      DNS_ALT_NAMES: 'puppet,puppet.ghn.me,puppetca,puppetca.ghn.me'
      JAVA_ARGS: '-Xms768m -Xmx768m'
  logs:
    hostname: log-agent
    image: gliderlabs/logspout:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    env_file: vault/logging.env
    command: syslog://$${LOG_SERVER_ADDRESS}:$${LOG_SERVER_PORT}
  ssl:
    image: vladgh/s3sync:latest
    hostname: ssl-sync-agent
    volumes_from:
      - data
    env_file: vault/ssl.env
  data:
    image: vladgh/vpm-data:latest
    hostname: data-agent
    environment:
      AWS_ASSETS_BUCKET: vladgh
    volumes:
      - .:/opt/vpm
      - ~/.aws:/root/.aws
      - /etc/localtime:/etc/localtime:ro
      - /opt/vgs
      - /var/local
      - ssl:/etc/puppetlabs/puppet/ssl
      - code:/etc/puppetlabs/code
      - vault:/etc/puppetlabs/vault
      - hieradata:/etc/puppetlabs/hieradata

volumes:
  ssl:
  code:
  vault:
  hieradata:
