version: '2'

services:
  server:
    image: vladgh/puppetserver:aws
    hostname: puppet.ghn.me
    ports:
      - '8140:8140'
    volumes_from:
      - r10k
    environment:
      AUTOSIGN: '/etc/puppetlabs/puppet/csr/sign'
      JAVA_ARGS: '-Xms768m -Xmx768m'
    entrypoint: /vpm/bin/run-puppetserver
    restart: 'on-failure:5'
  r10k:
    image: vladgh/r10k:latest
    hostname: r10k-agent
    volumes:
      - ~/.aws:/root/.aws:ro
      - .:/vpm
      - ./bin/csr-sign:/etc/puppetlabs/puppet/csr/sign:ro
      - ./.private/csr_cfg.yaml:/etc/puppetlabs/puppet/csr/cfg.yaml:ro
      - ./r10k.yaml:/etc/puppetlabs/r10k/r10k.yaml:ro
      - ./hiera.yaml:/etc/puppetlabs/puppet/hiera.yaml:ro
      - ssl:/etc/puppetlabs/puppet/ssl
      - code:/etc/puppetlabs/code
      - hieradata:/etc/puppetlabs/hieradata
      - /var/local
    working_dir: /vpm
    entrypoint: /vpm/bin/run-data-agent
    restart: 'no'
  logs:
    hostname: log-agent
    image: gliderlabs/logspout:latest
    volumes_from:
      - r10k
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /vpm/bin/run-log-agent
    restart: 'on-failure:5'

volumes:
  ssl:
  code:
  hieradata:
