HOSTS:
  xenial:
    platform: ubuntu-16.04-amd64
    hypervisor: vagrant
    box: puppetlabs/ubuntu-16.04-64-nocm
    mount_folders:
      data:
        from: ./../../../spec/fixtures/data
        to: /etc/puppetlabs/code/environments/production/data
      modules:
        from: ./../../../spec/fixtures/modules/r10k
        to: /etc/puppetlabs/code/environments/production/modules
      profiles:
        from: ./../../../spec/fixtures/modules/dist
        to: /etc/puppetlabs/code/environments/production/dist
CONFIG:
  type: aio
