---
# Green role data

# SSH
ssh::server_options:
  PermitRootLogin: 'no'
  PasswordAuthentication: 'no'
  LoginGraceTime: 30
  MaxStartups: '3:50:10'

# Docker
docker::docker_users:
  - cosmin
  - vlad

# Cron jobs
profile::base::cron_jobs:
  Backup:
    command: 'echo "Nothing yet" 2>&1 | /usr/bin/logger -t Backup'
    minute: '6'
    hour: '*/6'
