---
# Mini role data

# Sudo
sudo::configs:
  admins:
    content: "vlad ALL=(ALL) NOPASSWD: ALL"

# Docker
docker::docker_users: [vlad]

# Cron jobs
profile::base::cron_jobs:
  'Backup':
    command: 'echo "Nothing yet" 2>&1 | /usr/bin/logger -t Backup'
    minute: '6'
    hour: '*/6'
  'Docker Clean':
    command: '( docker images --no-trunc --quiet --filter dangling=true | xargs --no-run-if-empty docker rmi ) 2>&1 | /usr/bin/logger -t CleanUp'
    minute: '2'
    hour: '2'

# Samba
samba::server::workgroup: 'WORKGROUP'
samba::server::server_string: 'Mini'
samba::server::netbios_name: 'Mini'
samba::server::domain_master: true
samba::server::security: 'user'
samba::server::map_to_guest: 'Bad User'
samba::server::extra_global_options:
  - 'wins support = yes'
samba::server::shares:
  TV:
    - 'comment = TV'
    - 'path = /data/TV'
    - 'writeable = yes'
    - 'browseable = yes'
    - 'valid users = @sambashare'
    - 'create mask = 0664'
    - 'directory mask = 0775'
    - 'force group = sambashare'

# Miscellaneous
profile::misc::ignore_lid_switch: true
