---
# RHEA data

# SSH
ssh::server_options:
  PermitRootLogin: 'no'
  PasswordAuthentication: 'no'
  LoginGraceTime: 30
  MaxStartups: '3:50:10'
profile::base::ssh_authorized_keys:
  vgh_ed:
    ensure: present
    user: ubuntu
    type: ssh-ed25519
    key: AAAAC3NzaC1lZDI1NTE5AAAAIE0yyqRUbBGOW9PcYyuaUMaRi/EFwL59E3wwMn5dJAKQ
  vgh:
    ensure: present
    user: ubuntu
    type: ssh-rsa
    key: AAAAB3NzaC1yc2EAAAADAQABAAAEAQCuW/klOclhy5P4ipa24ISqChtLrDsNOO/mSkmavq5ypE8LR9ZP2Y9o52LYZ+Cp3QTYO46qIt4ubTEnWHjaCoY82P2zyFn7S4X16NvKLnjRCV4T5U0O2MM8ZlQbQqZPvuzsNI64yMUWOlVKXGohWFctCxafQWzcFebctARf50armUPF9A7hKm0qYa6aEWl1/dtMs8JVP3+bhZ0AlhkbLNiOSvT63I9Yakc11bedmtY07nSVOa1bWgHuGogdbexqLeaKLj6xCQKKM1iM7uaxXZyJGXTXrFV+VomnWZ3WKRaGRU9ctf+ki3nJJpEphTQsir6Dvg/qXL6fOW1pU2vd5XgV60FVd6kvFzy5yMzZfRMrwgG4241BGtOrnNGJEqo/9HGSNv9xX7Mm0mqX57rdIagZPwGaOk930dI0osYuyv09o0tqzwtJByEQ8rzhHHVu1L1l7SrhcfGq2ocjyyuZ33AY4aIY3JaretsfyahhleHCXwJUSJS3NDob8sqg/h5OBEnWLEcWBUm5+L1EeK332LM9tBwxrqFu5h6FwUuUeg3GtmREbgAKfA8ZvUwN4bl/nGzxrwjBjC+Y1ceaU30IrcbxEl6KdmO2vxivtGUlzkjAZ7yg7VpPEGOFpOqfjpGF5QeWcFXD2fnF5pg+YwCQcKoC6fdyhndkKQDOA87uVkFhi3z/QFO/PJ4rNxx5N69cdtSwB4mwJIb5KtAsyciYZpsmV/YrZhNT/7pHuPl3gERUIDpw6roo7/Lkeb19WAOc+9fDEDyFvHJIzO6+J5Kt5YdG2eXMRcGsxSRAUhl3Hfbtfok3qNh86wp39xd1mjzRoslXSGTfARzNb/CjpLA7Bs7vcEHCVYqEOm4Po2irWQeZZPJqaf37TjThS9WesZQLxYsi1KvOJYQiIJeOK2JbccRlRTl0DmcKQbwhMPNdf87LzcsQpDzKE3iESMImmgmGu+zcx/lUwjs7zjAuC/nTbPXPfs5KzniCxJuHMjC08IoP4c+FnWXRwA8WjggqKWBom9gY8FfxnI35Ic/aZj4z2LSzBDISGxk50QwS44Z1RX5x/W28HmIk54BFl527/R0Z1UYodHK1/tLjIdPAAOiRHaTBzR/6jKqnvH5WTvzxOH1jclMtm0TLpTon+VgDwkPG1TRx5icTbyz1YtlEq3pfPRnE2endKJub52Tpiym9qbPVNDs0vK5JwExufUAplwtVUw35C+OVKUhIMYTHibpZZJnBKCuQCBZhQ/qGN13vuPHqhIVKkrsgdVabOj8QrPpbpQaoYDiaWCpLLKMDgt0VyOtpWJKksjUlzDF+nU7B37alXxc2wEVLHOqDvSze5RPdAiIrQUyWDf1GVtPcF9aABH1F
  deploy:
    ensure: present
    user: ubuntu
    type: ssh-rsa
    key: AAAAB3NzaC1yc2EAAAADAQABAAABAQC+4vPJ554LgwIZ7qK2DoipJe9U2yuRwUZpTtjJ4EHqASn+KUbWX8XA7ipwLloQiWO25U5S4UjAxy3jcd2ykkQWD2XeXnE9qZZTgRAJfOpTKNIlng7NBPg9gHJcUADU8EXTd52sYQRl67inQpExb9TnshAAmrShh2T2cVqzybLdHbukchEHRUgKINp/Ci/zPffhv7yWKz4EUzvZdisRVgd3tuHJotvrHk18OOhSaGGlcuiig2AQgpd4MV7+yyyYoT0keOPiRrf3OAAnFMzaQbaoekDvwRg8GmCY3oFZVzsxehB+jTGj1ICz60L8qTN2oeD6zOw1EQWOQldNw5TnTuUz

# Python
python::python_pips:
  awscli:
    ensure: present

# Docker
docker::docker_users: [ubuntu]

# Cron jobs
profile::base::cron_jobs:
  'Backup':
    command: 'echo "Not yet" 2>&1 | /usr/bin/logger -t Backup'
    minute: '6'
    hour: '*/6'
  'Docker Clean':
    command: '( docker images --no-trunc --quiet --filter dangling=true | xargs --no-run-if-empty docker rmi ) 2>&1 | /usr/bin/logger -t CleanUp'
    minute: '2'
    hour: '2'

# Firewall rules
profile::linuxfw::rules:
  '11 accept OVH SLA monitoring':
    proto:  'icmp'
    action: 'accept'
    source: '92.222.184.0/24'
  '12 accept OVH SLA monitoring':
    proto:  'icmp'
    action: 'accept'
    source: '92.222.185.0/24'
  '13 accept OVH SLA monitoring':
    proto:  'icmp'
    action: 'accept'
    source: '92.222.186.0/24'
  '14 accept OVH SLA monitoring':
    proto:  'icmp'
    action: 'accept'
    source: '167.114.37.0/24'
  '15 accept OVH SLA monitoring':
    proto:  'icmp'
    action: 'accept'
    source: '198.100.154.30/32'
  '16 accept OVH SLA monitoring':
    proto:  'icmp'
    action: 'accept'
    source: '149.56.97.250/32'
  '21 allow access to HTTPS':
    proto:  'tcp'
    action: 'accept'
    dport:  '443'
